name: Generate Gradle Wrapper

on: workflow_dispatch

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: |
        gradle wrapper --gradle-version 8.5
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add gradlew* gradle/wrapper/
        git commit -m "Add Gradle wrapper files"
        git push
